version: "3.7"

services:
    web:
        build: .
        container_name: "web_django"
        volumes:
            - .:/usr/src/app
        command: /start

        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - postgres-db

    postgres-db:
        image: postgres:12.0-alpine
        env_file:
            - ./.env
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: