# Generated by Django 4.0.4 on 2022-05-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
