# Generated by Django 4.0.4 on 2022-05-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_delete_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.currency'),
            preserve_default=False,
        ),
    ]
