# Generated by Django 4.0.4 on 2022-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_order_orderitems_order_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', to='goods.item'),
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
